# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: compileTheCode
        steps:
          - bash: |
             hostname
             echo "list file in the current folder $(ls -l)"
             echo "java version: $(java --version)"
             echo "node version: $(node --version)"
             mvn clean install
             echo "---------------"
             ls -l
             ls -l target
  - stage: DeployToDev
    jobs:
      - job: devDeploy
  - stage: DeployToQa
    jobs:
      - job: qaDeploy
  - stage: DeployToProd
    jobs:
      - deployment: prodDeploy
        environment: Prod
        strategy: 
         runOnce:
           deploy:
             steps:
               - bash: |
                  echo "Deploying to Prod env"

      



