# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildTheApp
        steps:
          - bash: |
              ls -l
              pwd
              echo $PATH
              java --version
              node --version
  - stage: DevEnv
    jobs:
      - job: DeployToDev
  - stage: QaEnv
    jobs:
      - job: DeployToQa
  - stage: ProdEnv
    jobs: 
      - deployment: prodDeployment
        environment: Prod
        strategy:
         runOnce:
           deploy:
             steps:
               - script: echo Deploying to Prod environment


