# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: compileCode
        steps:
          - bash: |
             pwd
             hostname
             echo "list the files in the current dir: $(ls -l)"
  - stage: DeployToDev
    jobs:
      - job: devDeploy
  - stage: DeployToQa
    jobs:
      - job: qaDeploy
  - stage: DeployToProd
    jobs:
      - deployment: 
        environment: Prod
        strategy: 
         runOnce:
           deploy:
             steps:
               - bash: |
                  echo "Deploy to Production"



